### ISSUE TITLE
Leaderboard pre-processing

### ISSUE THREAD

**Issue by gerwolf** [ifo-institute/ifohack2023#24]
@muskuloes please have a look in the Leaderboard directory of ifohack2023 on the admin-prod-01, I started computing the overall score, the public score and the private score in `score_preprocessing.ipynb`. Only the public score will be displayed in the leaderboard app.

I'll finalise the script by Tuesday probably. I'll also need to figure out the Gitea credentials for the admin-prod-01 VM...

**Comment by muskuloes** [comment]
Hi,

For the scoring code checkout the `scoring PR`. 
One thing:
- I can't make it so that the participants only submit one file. This is because if *I don't know the team names in advance*, I am not able to pick exactly the required file from the submission folder (because they might have multiple csv files in there and they might not delete the unnecessary ones).

I therefore propose that they have a `submission` folder, with two files.
1. The predictions, `<teamname>_eval_submission.csv`.
2. a json file with their team meta information called `team.json`:
```json
{
  "name": "suns",
  "members": ["Leo Messi", "Cristian Ronaldo"]
}
```
